import { ImageResponse } from 'next/og';
import type { NextRequest } from 'next/server';

import { OgCard, ogSubtitle, OG_SIZE } from '@/lib/og-card';

/**
 * Link-preview cards for routes with dynamic segments.
 *
 * Next's file convention (opengraph-image.tsx) handles the site-level card at
 * src/app/opengraph-image.tsx, where it is the right tool. The cards for
 * dynamic segments are built here instead, for two reasons.
 *
 * The calling page passes the text rather than this route looking it up. The
 * page has already loaded the post or the project, so this avoids a second
 * database read on a request made by a social scraper rather than a person —
 * and for a post, that read could fail independently of the page it belongs to.
 *
 * And the URL is an ordinary one this repo constructs (src/lib/og-url.ts), so
 * a test can assert exactly what a page advertises and fetch it. With the file
 * convention the URL is generated by the framework, which makes "is the card
 * actually reachable" a question only a browser can answer. It is worth being
 * able to answer it in CI, because a link preview is often the first thing
 * anyone sees of this site and nothing about a broken one is visible from
 * inside the app.
 *
 * Inputs are untrusted — anyone can call this with any query string. They are
 * length-capped and rendered as text into an image, never into HTML, so the
 * worst outcome is an ugly card.
 */

/** Text is clamped so a long query string cannot produce an unreadable image. */
const MAX_TITLE = 120;
const MAX_SUBTITLE = 160;
const MAX_EYEBROW = 40;

function clamp(value: string | null, max: number): string {
  return (value ?? '').replace(/\s+/g, ' ').trim().slice(0, max);
}

export function GET(request: NextRequest) {
  const params = request.nextUrl.searchParams;

  const title = clamp(params.get('title'), MAX_TITLE) || 'Antonio Luis Santos';
  const subtitle = clamp(params.get('subtitle'), MAX_SUBTITLE);
  const eyebrow = clamp(params.get('eyebrow'), MAX_EYEBROW) || '~/portfolio $ whoami';
  const chips = (params.get('chips') ?? '')
    .split(',')
    .map(chip => chip.trim().slice(0, 24))
    .filter(Boolean)
    .slice(0, 4);

  return new ImageResponse(
    (
      <OgCard
        eyebrow={eyebrow}
        title={title}
        subtitle={subtitle ? ogSubtitle(subtitle) : undefined}
        chips={chips}
      />
    ),
    OG_SIZE
  );
}
