"use client";

import AIGeneratedIndicator from "./AIGeneratedIndicator";

export default function AIAnswerDemo() {
  return (
    <div className="max-w-2xl mx-auto p-6 space-y-6">
      <h2 className="text-2xl font-bold text-center mb-8">AI Answer Indicator Demo</h2>
      
      {/* Example 1: FAQ Answer */}
      <div className="bg-white dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700 relative">
        <AIGeneratedIndicator 
          position="top-right"
          message="This answer is generated by AI beyond the FAQ dataset."
        />
        <h3 className="font-semibold text-lg mb-2">What services do you offer?</h3>
        <p className="text-gray-700 dark:text-gray-300">
          I offer comprehensive web development services including responsive websites, 
          e-commerce solutions, AI chatbot integration, and custom backend development. 
          All packages include 30-day support and are designed to scale with your business needs.
        </p>
      </div>

      {/* Example 2: Chat Response */}
      <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-4 border border-blue-200 dark:border-blue-800 relative">
        <AIGeneratedIndicator 
          position="top-left"
          message="This response was generated by AI and may not be 100% accurate."
        />
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-white text-sm font-bold">
            AI
          </div>
          <div>
            <p className="text-blue-900 dark:text-blue-100">
              Based on your requirements, I recommend the Enterprise package which includes 
              advanced AI chatbot capabilities, custom backend integration, and priority support.
            </p>
          </div>
        </div>
      </div>

      {/* Example 3: Different positions */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700 relative h-24">
          <AIGeneratedIndicator 
            position="bottom-left"
            message="AI-generated content"
          />
          <p className="text-sm text-gray-600 dark:text-gray-400">Bottom-left indicator</p>
        </div>
        
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700 relative h-24">
          <AIGeneratedIndicator 
            position="bottom-right"
            message="AI-generated content"
          />
          <p className="text-sm text-gray-600 dark:text-gray-400">Bottom-right indicator</p>
        </div>
      </div>

      {/* Usage Instructions */}
      <div className="bg-yellow-50 dark:bg-yellow-950/20 rounded-lg p-4 border border-yellow-200 dark:border-yellow-800">
        <h4 className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">Usage Instructions:</h4>
        <ul className="text-sm text-yellow-700 dark:text-yellow-300 space-y-1">
          <li>• Hover over the green dot to see the AI indicator message</li>
          <li>• The dot has a subtle pulse animation to draw attention</li>
          <li>• Position can be customized: top-left, top-right, bottom-left, bottom-right</li>
          <li>• Message can be customized for different contexts</li>
          <li>• Fully responsive and works in both light and dark modes</li>
        </ul>
      </div>
    </div>
  );
}
