"use client";

import AIGeneratedIndicator from "./AIGeneratedIndicator";

const faqData = [
  {
    question: "What technologies do you specialize in?",
    answer: "I specialize in Java, C++, IBM ODM, HTML, CSS, Next.js, TailwindCSS, PostgreSQL, Sanity, and Wix. I'm also expanding into automation testing and AI-driven workflow tools like Zapier.",
    isAIGenerated: false
  },
  {
    question: "How long does a typical project take?",
    answer: "Project timelines vary based on complexity. A basic website typically takes 1-2 weeks, while enterprise solutions with custom integrations can take 4-8 weeks. I provide detailed timelines during our initial consultation.",
    isAIGenerated: true
  },
  {
    question: "Do you provide ongoing support?",
    answer: "Yes, all packages include 30-day support. For enterprise clients, I offer extended support plans with priority response times and dedicated maintenance windows.",
    isAIGenerated: false
  },
  {
    question: "Can you integrate with our existing systems?",
    answer: "Absolutely! I have extensive experience with enterprise system integrations, API development, and custom backend solutions. I can work with your existing tech stack and ensure seamless data flow between systems.",
    isAIGenerated: true
  }
];

export default function FAQExample() {
  return (
    <div className="max-w-4xl mx-auto p-6">
      <h2 className="text-3xl font-bold text-center mb-8">Frequently Asked Questions</h2>
      
      <div className="space-y-4">
        {faqData.map((faq, index) => (
          <div 
            key={index}
            className="bg-white dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700 relative hover:shadow-md transition-shadow"
          >
            {faq.isAIGenerated && (
              <AIGeneratedIndicator 
                position="top-right"
                message="This answer is generated by AI beyond the FAQ dataset."
              />
            )}
            
            <h3 className="font-semibold text-lg mb-3 text-gray-900 dark:text-gray-100">
              {faq.question}
            </h3>
            
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              {faq.answer}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-blue-50 dark:bg-blue-950/20 rounded-lg p-4 border border-blue-200 dark:border-blue-800">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-3 h-3 bg-green-500 rounded-full"></div>
          <span className="text-sm font-medium text-blue-800 dark:text-blue-200">
            AI-Generated Content Indicator
          </span>
        </div>
        <p className="text-sm text-blue-700 dark:text-blue-300">
          Hover over the green dots to see which answers are AI-generated beyond our FAQ dataset.
        </p>
      </div>
    </div>
  );
}
