/**
 * research.test.ts
 *
 * Guard rail:
 *   N24 — a contents entry must point at a heading that exists
 *
 * The contents list and the headings it links to are generated by two
 * different functions in two different files: headingId() here, and
 * headingSlug() inside MarkdownBody. They shipped out of step the first time —
 * react-markdown adds no ids at all, so every link in a 22-section contents
 * list scrolled nowhere, and nothing failed. A dead anchor is invisible to
 * every check except clicking it.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { getResearchDoc, getResearchDocs, headingId } from '../research';

const ROOT = path.resolve(__dirname, '../../..');

describe('documents load', () => {
  it('finds at least one, and every one has the fields the page needs', () => {
    const docs = getResearchDocs();
    expect(docs.length).toBeGreaterThan(0);

    for (const doc of docs) {
      expect(doc.title, doc.slug).toBeTruthy();
      expect(doc.abstract.length, `${doc.slug} abstract`).toBeGreaterThan(80);
      expect(doc.date, `${doc.slug} date`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it('extracts the section list', () => {
    const doc = getResearchDoc(getResearchDocs()[0].slug)!;
    expect(doc.sections.length).toBeGreaterThan(3);
    expect(doc.wordCount).toBeGreaterThan(800);
  });

  it('returns null for an unknown slug', () => {
    expect(getResearchDoc('does-not-exist')).toBeNull();
  });

  it('refuses a slug that would escape the content directory', () => {
    // The slug arrives from a URL segment, so it is untrusted input to a
    // path join.
    for (const slug of ['../../../etc/passwd', 'a/../../b', 'a b', 'UPPER', '']) {
      expect(getResearchDoc(slug), slug).toBeNull();
    }
  });
});

describe('N24 — every contents link points at a real heading', () => {
  /**
   * The renderer's id generator, extracted from source rather than imported:
   * MarkdownBody is a client component full of JSX, and this test runs in the
   * node project. Comparing the implementations directly is the point — if
   * one is edited and the other is not, this fails.
   */
  function rendererSlugify(text: string): string {
    const source = readFileSync(
      path.join(ROOT, 'src/components/ui/MarkdownBody.tsx'),
      'utf8'
    );

    // Pin the transformation steps rather than re-implementing them blind.
    expect(source, 'MarkdownBody must still derive ids from heading text').toContain(
      'function headingSlug'
    );
    expect(source, 'headings must carry the id').toMatch(/id=\{headingSlug\(children\)\}/);

    return text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-');
  }

  it('the two id generators agree', () => {
    const samples = [
      'The question',
      '3. My core argument',
      'Air gaps, and what they actually mean',
      'Capability versus agency',
      'What has actually been demonstrated',
      'Why now',
    ];

    for (const sample of samples) {
      expect(headingId(sample), sample).toBe(rendererSlugify(sample));
    }
  });

  it('every section id in every document is non-empty and unique', () => {
    for (const meta of getResearchDocs()) {
      const doc = getResearchDoc(meta.slug)!;
      const ids = doc.sections.map(section => section.id);

      for (const id of ids) {
        expect(id, `${meta.slug}: empty id`).not.toBe('');
        expect(id, `${meta.slug}: ${id}`).toMatch(/^[a-z0-9-]+$/);
      }

      expect(new Set(ids).size, `${meta.slug} has duplicate section ids`).toBe(ids.length);
    }
  });

  it('ignores headings inside code fences', () => {
    // The documents contain ASCII diagrams in fenced blocks, and a line
    // starting with ## inside one is art, not a section.
    const doc = getResearchDoc(getResearchDocs()[0].slug)!;
    for (const section of doc.sections) {
      expect(doc.body).toContain(`## ${section.title}`);
    }
  });
});

describe('the documents cite what they claim', () => {
  it('every external link is to a primary source', () => {
    // A news write-up of a paper is where a claim drifts from what the paper
    // said. These documents cite the paper.
    const allowed = [
      'arxiv.org',
      'openai.com',
      'anthropic.com',
      'internationalaisafetyreport.org',
      'deepmind.google',
      'nist.gov',
    ];

    for (const meta of getResearchDocs()) {
      const doc = getResearchDoc(meta.slug)!;

      for (const match of doc.body.matchAll(/https?:\/\/([^\s)<>"'\]/]+)/g)) {
        const host = match[1].toLowerCase();
        const ok = allowed.some(domain => host === domain || host.endsWith(`.${domain}`));
        expect(ok, `${meta.slug} cites a non-primary source: ${host}`).toBe(true);
      }
    }
  });
});
